### ISSUE TITLE
Configuration Table Editor - Facility - Rooms discards new row data

### ISSUE THREAD

**Issue by Iiridayn** [olszowka/Zambia#116] opened 2021-06-05 17:44 UTC
Using the Configuration Table Editor to add new rooms to the database results in it discarding all new rows and only updating the single current existing row.

**Comment by bcholmes** [comment] 2021-06-06 14:26
I noticed a similar behaviour, today, with session tags.

**Comment by bcholmes** [comment] 2021-06-13 14:29
Some debug notes:

1. The request from the browser to the server appears correct.
2. The server logs the following message:

`mysqli_stmt_bind_param(): Number of elements in type definition string doesn't match number of bind variables in /var/www/wiscontest.bcholmes.org/db_functions.php on line 57`

**Comment by olszowka** [comment] 2021-06-13 15:50
Fixed with PR #119

**Closed by olszowka** 2021-06-13 15:50 UTC

**Comment by Iiridayn** [comment] 2021-08-17 18:00
This is not fixed; just pulled the latest code, and I still cannot add any entries to the Rooms table.

**Comment by olszowka** [comment] 2021-08-17 18:08
@liridayn I suspect your issue is #125.

**Comment by Iiridayn** [comment] 2021-08-17 18:51
Possibly - not sure how the internals work at present. However, as I am the person who opened this issue and the Room table does in fact still discard new row data, I thought it important to bring to light that the issue was unresolved. Hopefully this #116 is a duplicate of #125 :).

**Comment by lostcarpark** [comment] 2021-08-28 00:55
This should be fixed by pull request #135.
The cause was attempting to insert empty strings into the time fields.

**Comment by bcholmes** [comment] 2021-08-30 04:53
It might be important to mention that PR #135 isn't on master.
